### PR TITLE
Deploy with github pages and actions

### LINKED ISSUE #56: 【建议】使用 GitHub Pages 搭载项目
**您有什么更好的想法吗**

直接从 GitHub 看 README 太痛苦了，分享链接也是一长串，不如搭个 Pages。

**详述目前的问题和可能的解决办法**

Ref: https://zju-turing.github.io/TuringCourses/

**您还有什么要说的吗**

无。

### PR DESCRIPTION
**Pull request by CookiePieWw**
The change log seems too long here. It's because I just removed all of the irrelevant files since they are all shared on onedrive and none of the markdown summaries of courses uses these files' urls on GitHub (or mkdocs will complain about it). So checkout my last few commits for review is much simpler.

I changed a few lines in CONTRIBUTING.md, and the index page generated by README.md needs a few changes as well (emoji markups). But let's leave it behind: if it goes well, we'll have a (maybe) clean and fine website! :)

close #56

### CODE REVIEW

**Comment by skyleaworlder** [comment]
I apologize for not realizing earlier that you have deleted a huge number of files from the repository in order to use `mkdocs`.

From my perspective, this is highly undesirable. You mentioned that these files might have been obtained in other places, and I also acknowledge that many of them may no longer be relevant to be kept in this repository (such as lab descriptions, as they may change every year).

However, documents such as past exam outlines are valuable, which are also going to be removed in this PR. Some of them can be hardly found in current search engines, and relying solely on the inheritence between senior and junior students could result in the massive loss of a significant amount of docs. Preventing such an occurrence is exactly one of the purposes of this project!

**Comment by CookiePieWw** [comment]
You're right, it's not proper to remove all of the irrelevant files. A better choice is to keep the files and add them at the end of the summaries.

Now we can access the files directly through links under the summaries, [example here](https://cookiepieww.github.io/TJCS-Course/%E5%A4%A7%E4%BA%8C%E4%B8%8B/100396_%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B3%BB%E7%BB%9F%E5%8E%9F%E7%90%86/#_4)

**Comment by skyleaworlder** [comment]
LGTM!

**Comment by CookiePieWw** [comment]
~~Hi @skyleaworlder, you may forget to deploy the gh-pages branch with GitHub Pages in this repository.~~

~~Oh sry, it seems I need to add a deploy part to the workflow instead of deploying it manually.~~

Ah I tried to figured it out. The GitHub Pages in settings should be configured.

**Comment by skyleaworlder** [comment]
The current default setting of GitHub Pages is to deploy a site from a workflow. I tried several times but I still failed.

Now I use the `gh-pages` branch as the source, and it works well.

**Pull request merged**
